services:
  app:
    image: public.ecr.aws/j7u4k4y6/app:latest
    ports:
      - 80:8080
    networks:
      - app
    environment:
      - DATABASE_USER=${DATABASE_USER:-admin}
      - DATABASE_URI=${DATABASE_URI:-sqlite:////tmp/test.db}
      - BUCKET_NAME=${BUCKET_NAME:-sc-lab3-app-bucket}
      - AWS_DEFAULT_REGION=ap-southeast-1
    volumes:
      - /var/log:/var/log

networks:
  app:
    driver: bridge
